@php
    $status = $record->status;
    $isWinner = $mode === 'bidder';
    $canInspect = $mode === 'end_user' && $status === \App\Models\ContractImplementation::INFRA_FOR_INSPECTION;
    $canAct = in_array($mode, ['admin', 'staff'], true) && in_array($status, [\App\Models\ContractImplementation::INFRA_RECOMMENDED, \App\Models\ContractImplementation::INFRA_ACCEPTED, \App\Models\ContractImplementation::INFRA_PAYMENT_PROCESSING, \App\Models\ContractImplementation::INFRA_PAID], true);
@endphp
<section class="ui-card" style="padding:22px;margin-bottom:20px">
    <div style="display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap"><div><small>{{ $award->project->reference_no }} &middot; INFRASTRUCTURE</small><h2 style="margin:6px 0">{{ $award->project->title }}</h2><p>Winning supplier: {{ $award->bid?->user?->company ?: $award->bid?->user?->name }} &middot; NTP: {{ $award->bid?->notice_to_proceed_at?->timezone('Asia/Manila')->format('M d, Y') }}</p></div><strong>{{ $record->isConfigured() ? $record->label() : 'Awaiting signed contract details' }}</strong></div>
    @if(! $record->isConfigured() && in_array($mode, ['admin', 'staff'], true))
        <form method="POST" enctype="multipart/form-data" action="{{ route($mode === 'staff' ? 'staff.infrastructure.configure' : 'admin.infrastructure.configure', $award) }}" class="ui-card" style="padding:16px;margin-top:12px">@csrf
            <h3>Record terms from signed contract</h3><p>Enter the actual completion deadline and site/location from the signed contract. NTP date is shown separately and is not treated as the deadline.</p>
            <label>Contract completion deadline<input type="date" name="delivery_deadline" required></label><label>Work site / delivery location<input name="delivery_location" maxlength="255" required></label><label>Signed contract reference<input name="signed_contract_reference" required></label>
            <h4>Contract work items and quantities</h4><div id="infra-items-{{ $award->id }}"><div><input name="contract_items[0][description]" placeholder="Work item" required><input name="contract_items[0][quantity]" type="number" step="0.01" min="0.01" placeholder="Quantity" required><input name="contract_items[0][unit]" placeholder="Unit" required></div></div>
            <label>Remarks<textarea name="remarks" required></textarea></label><label>Signed contract / supporting proof<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required></label><button class="ui-btn ui-btn--primary">Save infrastructure terms</button>
        </form>
    @elseif($record->isConfigured())
        <div style="margin:16px 0"><p><b>Contract completion deadline:</b> {{ $record->effectiveDeadline()?->format('M d, Y') }} &middot; <b>Work site:</b> {{ $record->delivery_location }} &middot; <b>Contract reference:</b> {{ $record->signed_contract_reference }}</p><table class="ui-table"><thead><tr><th>Work item</th><th>Contract quantity</th><th>Unit</th></tr></thead><tbody>@foreach($record->contract_items as $item)<tr><td>{{ $item['description'] }}</td><td>{{ $item['quantity'] }}</td><td>{{ $item['unit'] }}</td></tr>@endforeach</tbody></table></div>
        @if($isWinner && in_array($status, [\App\Models\ContractImplementation::INFRA_IN_PROGRESS, \App\Models\ContractImplementation::INFRA_FOR_CORRECTION], true))
            <form method="POST" enctype="multipart/form-data" action="{{ route('bidder.infrastructure.progress', $award) }}" class="ui-card" style="padding:16px">@csrf<h3>{{ $status === \App\Models\ContractImplementation::INFRA_FOR_CORRECTION ? 'Submit corrected work' : 'Submit progress update' }}</h3><label>Progress (%)<input name="progress_percent" type="number" min="0" max="100" required></label><label>Milestone / work completed<input name="milestone" maxlength="255" required></label><label>Remarks<textarea name="remarks" required></textarea></label><label>Photo, report, or progress proof<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required></label><label><input type="checkbox" name="request_inspection" value="1"> Work is ready; request site inspection</label><button class="ui-btn ui-btn--primary">Submit update</button></form>
        @endif
        @if($canInspect)
            <form method="POST" enctype="multipart/form-data" action="{{ route('end-user.infrastructure.inspect', $award) }}" class="ui-card" style="padding:16px">@csrf<h3>Record site inspection</h3><label>Result<select name="outcome" required><option value="recommend_acceptance">Recommend formal acceptance</option><option value="correction">Request correction / reinspection</option></select></label><label>Findings<textarea name="findings" required></textarea></label><label>Deficiencies, if any<textarea name="deficiencies"></textarea></label><label>Remarks<textarea name="remarks" required></textarea></label><label>Inspection report / supporting document<input type="file" name="document" required></label><button class="ui-btn ui-btn--primary">Record inspection</button></form>
        @endif
        @if($canAct)
            <form method="POST" enctype="multipart/form-data" action="{{ route($mode === 'staff' ? 'staff.infrastructure.action' : 'admin.infrastructure.action', $award) }}" class="ui-card" style="padding:16px">@csrf<h3>Authorized LGU contract action</h3><label>Next status<select name="action" required>@if($status === \App\Models\ContractImplementation::INFRA_RECOMMENDED)<option value="accept">Formally accept completed work</option>@elseif($status === \App\Models\ContractImplementation::INFRA_ACCEPTED)<option value="payment_processing">Record payment processing</option>@elseif($status === \App\Models\ContractImplementation::INFRA_PAYMENT_PROCESSING)<option value="paid">Record paid status</option>@elseif($status === \App\Models\ContractImplementation::INFRA_PAID)<option value="complete">Mark contract implementation completed</option>@endif</select></label><label>Remarks<textarea name="remarks" required></textarea></label><label>Acceptance/payment/completion record<input type="file" name="document" required></label><button class="ui-btn ui-btn--primary">Record action</button><p>Status tracking only; this system does not transfer funds.</p></form>
        @endif
    @elseif($mode === 'bidder')<p>Infrastructure terms are being recorded by the BAC from the signed contract.</p>@endif
    <h3 style="margin-top:20px">Activity history</h3><ol style="padding-left:22px">@forelse($record->events as $event)<li style="padding:8px 0"><b>{{ str($event->action)->replace('_',' ')->title() }}</b> &middot; {{ $event->occurred_at?->timezone('Asia/Manila')->format('M d, Y g:i A') }} &middot; {{ $event->actor?->name ?? 'LGU user' }}@if($event->remarks) &mdash; {{ $event->remarks }}@endif @if($event->document_path)<a href="{{ route('infrastructure.document', $event) }}">View supporting document</a>@endif</li>@empty<li>No progress activity has been recorded.</li>@endforelse</ol>
</section>
